# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/protou/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/htc/protou/proprietary/usr/keylayout/qwerty.kl:system/usr/keylayout/qwerty.kl \
    vendor/htc/protou/proprietary/usr/keylayout/protou-keypad.kl:system/usr/keylayout/protou-keypad.kl \
    vendor/htc/protou/proprietary/usr/keylayout/projector-Keypad.kl:system/usr/keylayout/projector-Keypad.kl \
    vendor/htc/protou/proprietary/usr/keylayout/himax-touchscreen.kl:system/usr/keylayout/himax-touchscreen.kl \
    vendor/htc/protou/proprietary/usr/keylayout/h2w_headset.kl:system/usr/keylayout/h2w_headset.kl \
    vendor/htc/protou/proprietary/usr/keylayout/Generic.kl:system/usr/keylayout/Generic.kl \
    vendor/htc/protou/proprietary/usr/keylayout/AVRCP.kl:system/usr/keylayout/AVRCP.kl \
    vendor/htc/protou/proprietary/usr/keychars/Virtual.kcm:system/usr/keychars/Virtual.kcm \
    vendor/htc/protou/proprietary/usr/keychars/qwerty.kcm:system/usr/keychars/qwerty.kcm \
    vendor/htc/protou/proprietary/usr/keychars/qwerty2.kcm:system/usr/keychars/qwerty2.kcm \
    vendor/htc/protou/proprietary/usr/keychars/Generic.kcm:system/usr/keychars/Generic.kcm \
    vendor/htc/protou/proprietary/usr/idc/projector_input.idc:system/usr/idc/projector_input.idc \
    vendor/htc/protou/proprietary/usr/idc/himax-touchscreen.idc:system/usr/idc/himax-touchscreen.idc \
    vendor/htc/protou/proprietary/lib/libsc-a2xx.so:system/lib/libsc-a2xx.so \
    vendor/htc/protou/proprietary/lib/libOpenVG.so:system/lib/libOpenVG.so \
    vendor/htc/protou/proprietary/lib/libOmxVidEnc.so:system/lib/libOmxVidEnc.so \
    vendor/htc/protou/proprietary/lib/libOmxMpeg4Dec.so:system/lib/libOmxMpeg4Dec.so \
    vendor/htc/protou/proprietary/lib/libOmxH264Dec.so:system/lib/libOmxH264Dec.so \
    vendor/htc/protou/proprietary/lib/libOlaEngine.so:system/lib/libOlaEngine.so \
    vendor/htc/protou/proprietary/lib/libOlaEngineNew.so:system/lib/libOlaEngineNew.so \
    vendor/htc/protou/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/htc/protou/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/htc/protou/proprietary/lib/libmmipl.so:system/lib/libmmipl.so \
    vendor/htc/protou/proprietary/lib/libmmcamera_wavelet_lib.so:system/lib/libmmcamera_wavelet_lib.so \
    vendor/htc/protou/proprietary/lib/libmmcamera_statsproc31.so:system/lib/libmmcamera_statsproc31.so \
    vendor/htc/protou/proprietary/lib/libmmcamera_rawchipproc.so:system/lib/libmmcamera_rawchipproc.so \
    vendor/htc/protou/proprietary/lib/libmmcamera_interface2.so:system/lib/libmmcamera_interface2.so \
    vendor/htc/protou/proprietary/lib/libmmcamera_image_stab.so:system/lib/libmmcamera_image_stab.so \
    vendor/htc/protou/proprietary/lib/libmmcamera_hdr_lib.so:system/lib/libmmcamera_hdr_lib.so \
    vendor/htc/protou/proprietary/lib/libmmcamera_frameproc.so:system/lib/libmmcamera_frameproc.so \
    vendor/htc/protou/proprietary/lib/libmmcamera_faceproc.so:system/lib/libmmcamera_faceproc.so \
    vendor/htc/protou/proprietary/lib/libmm-adspsvc.so:system/lib/libmm-adspsvc.so \
    vendor/htc/protou/proprietary/lib/libhtc_ril.so:system/lib/libhtc_ril.so \
    vendor/htc/protou/proprietary/lib/libhtc_acoustic.so:system/lib/libhtc_acoustic.so \
    vendor/htc/protou/proprietary/lib/libgsl.so:system/lib/libgsl.so \
    vendor/htc/protou/proprietary/lib/libchromatix_s5k4e5yx_preview.so:system/lib/libchromatix_s5k4e5yx_preview.so \
    vendor/htc/protou/proprietary/lib/libchromatix_s5k4e5yx_hdr.so:system/lib/libchromatix_s5k4e5yx_hdr.so \
    vendor/htc/protou/proprietary/lib/libchromatix_s5k4e5yx_default_video.so:system/lib/libchromatix_s5k4e5yx_default_video.so \
    vendor/htc/protou/proprietary/lib/libchromatix_s5k4e1_preview.so:system/lib/libchromatix_s5k4e1_preview.so \
    vendor/htc/protou/proprietary/lib/libchromatix_s5k4e1_default_video.so:system/lib/libchromatix_s5k4e1_default_video.so \
    vendor/htc/protou/proprietary/lib/libchromatix_ov5693_preview.so:system/lib/libchromatix_ov5693_preview.so \
    vendor/htc/protou/proprietary/lib/libchromatix_ov5693_hdr.so:system/lib/libchromatix_ov5693_hdr.so \
    vendor/htc/protou/proprietary/lib/libchromatix_ov5693_default_video.so:system/lib/libchromatix_ov5693_default_video.so \
    vendor/htc/protou/proprietary/lib/libcamerapp.so:system/lib/libcamerapp.so \
    vendor/htc/protou/proprietary/lib/libcameraface.so:system/lib/libcameraface.so \
    vendor/htc/protou/proprietary/lib/libaudioeq.so:system/lib/libaudioeq.so \
    vendor/htc/protou/proprietary/lib/hw/sensors.protou.so:system/lib/hw/sensors.protou.so \
    vendor/htc/protou/proprietary/lib/hw/camera.msm7k.so:system/lib/hw/camera.msm7k.so \
    vendor/htc/protou/proprietary/lib/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
    vendor/htc/protou/proprietary/lib/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
    vendor/htc/protou/proprietary/lib/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/htc/protou/proprietary/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
    vendor/htc/protou/proprietary/lib/egl/eglsubAndroid.so:system/lib/egl/eglsubAndroid.so \
    vendor/htc/protou/proprietary/etc/soundimage/srs_global.cfg:system/etc/soundimage/srs_global.cfg \
    vendor/htc/protou/proprietary/etc/soundimage/srs_geq10.cfg:system/etc/soundimage/srs_geq10.cfg \
    vendor/htc/protou/proprietary/etc/soundimage/srsfx_trumedia_voice.cfg:system/etc/soundimage/srsfx_trumedia_voice.cfg \
    vendor/htc/protou/proprietary/etc/soundimage/srsfx_trumedia_music.cfg:system/etc/soundimage/srsfx_trumedia_music.cfg \
    vendor/htc/protou/proprietary/etc/soundimage/srsfx_trumedia_movie.cfg:system/etc/soundimage/srsfx_trumedia_movie.cfg \
    vendor/htc/protou/proprietary/etc/soundimage/srsfx_trumedia_51.cfg:system/etc/soundimage/srsfx_trumedia_51.cfg \
    vendor/htc/protou/proprietary/etc/soundimage/srs_bypass.cfg:system/etc/soundimage/srs_bypass.cfg \
    vendor/htc/protou/proprietary/etc/media_profiles.xml:system/etc/media_profiles.xml \
    vendor/htc/protou/proprietary/etc/firmware/yamato_pm4.fw:system/etc/firmware/yamato_pm4.fw \
    vendor/htc/protou/proprietary/etc/firmware/yamato_pfp.fw:system/etc/firmware/yamato_pfp.fw \
    vendor/htc/protou/proprietary/etc/firmware/fw_bcm4330_p2p_b2.bin:system/etc/firmware/fw_bcm4330_p2p_b2.bin \
    vendor/htc/protou/proprietary/etc/firmware/fw_bcm4330_p2p_b1.bin:system/etc/firmware/fw_bcm4330_p2p_b1.bin \
    vendor/htc/protou/proprietary/etc/firmware/fw_bcm4330_b2.bin:system/etc/firmware/fw_bcm4330_b2.bin \
    vendor/htc/protou/proprietary/etc/firmware/fw_bcm4330_b1.bin:system/etc/firmware/fw_bcm4330_b1.bin \
    vendor/htc/protou/proprietary/etc/firmware/fw_bcm4330_apsta_b2.bin:system/etc/firmware/fw_bcm4330_apsta_b2.bin \
    vendor/htc/protou/proprietary/etc/firmware/fw_bcm4330_apsta_b1.bin:system/etc/firmware/fw_bcm4330_apsta_b1.bin \
    vendor/htc/protou/proprietary/etc/firmware/BCM4330B1_002.001.003.0833.0845.hcd:system/etc/firmware/BCM4330B1_002.001.003.0833.0845.hcd \
    vendor/htc/protou/proprietary/etc/AudioPreProcess.csv:system/etc/AudioPreProcess.csv \
    vendor/htc/protou/proprietary/etc/AudioPara4_WB.csv:system/etc/AudioPara4_WB.csv \
    vendor/htc/protou/proprietary/etc/AudioPara4.csv:system/etc/AudioPara4.csv \
    vendor/htc/protou/proprietary/etc/AudioFilter.csv:system/etc/AudioFilter.csv \
    vendor/htc/protou/proprietary/etc/AudioBTID.csv:system/etc/AudioBTID.csv \
    vendor/htc/protou/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/htc/protou/proprietary/bin/mm-venc-omx-test:system/bin/mm-venc-omx-test \
    vendor/htc/protou/proprietary/bin/mm-vdec-omx-test:system/bin/mm-vdec-omx-test \
    vendor/htc/protou/proprietary/bin/mm-qcamera-testsuite-client:system/bin/mm-qcamera-testsuite-client \
    vendor/htc/protou/proprietary/bin/mm-qcamera-test:system/bin/mm-qcamera-test \
    vendor/htc/protou/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    vendor/htc/protou/proprietary/bin/mm-qcamera-app:system/bin/mm-qcamera-app \
    vendor/htc/protou/proprietary/bin/mm-jpeg-enc-test-client:system/bin/mm-jpeg-enc-test-client \
    vendor/htc/protou/proprietary/bin/mm-jpeg-enc-test:system/bin/mm-jpeg-enc-test \
    vendor/htc/protou/proprietary/bin/mm-jpeg-dec-test:system/bin/mm-jpeg-dec-test \
    vendor/htc/protou/proprietary/bin/lsc_camera:system/bin/lsc_camera \
    vendor/htc/protou/proprietary/bin/awb_camera:system/bin/awb_camera
